### ISSUE TITLE
no need to push to master, all of us breaks down!!!!111!!!!!

### ISSUE THREAD

**Issue by spavlovich001** [pashinin/workgroups2#101]
No need to push to master, all of us breaks down xD. Use develop branch

**Comment by redguardtoo** [comment]
What's the problem? Could you give me more details?

**Comment by spavlovich001** [comment]
1. wg-prefixed-map not found
```
:bind ((:map workgroups-mode-map
              ([remap wg-save-session] . wg-project-sess-save)
              ([remap wg-open-session] . wg-project-sess-open))
         (:map wg-prefixed-map
               ("C-s" . wg-project-sess-save)
               ("C-f" . wg-project-sess-open))))
```

2. this instruction broken all map C-c
```
(workgroups-mode 1)
```

**Comment by redguardtoo** [comment]
@spavlovich001  , as I tested, latest workgroups2 is ok.

See README,
```
Use M-x wg-create-workgroup to save current windows layout.

Use M-x wg-open-workgroup to open saved windows layout.
```

Please note old command `wg-switch-to-workgroup` is now alias of `wg-open-workgroup`.

You can use above commands without directly without turning on any minor mode.

I plan to remove the default keybinding and minor mode but the above commands are still valid. The default key bindings of minor mode might conflict with other minor modes.Using `global-set-key` is much better.
