### ISSUE TITLE
Melpa supplies a non-functional package

### ISSUE THREAD

**Issue by sirikid** [pashinin/workgroups2#102]
Hi, @redguardtoo!

It seems like you have been working a lot on the package lately. Unfortunately melpa every day builds the latest commit from the tracked branch, in this case master. Please use dedicated branches to prevent users from getting development versions of the package or create a dedicated release branch and set up melpa's recipe to use it.

**Comment by redguardtoo** [comment]
sure

**Comment by sirikid** [comment]
For people whose setup broke: you can use the melpa-stable version for now.

**Comment by redguardtoo** [comment]
@sirikid , as I tested, latest workgroups2 is ok.

See README,
```
Use M-x wg-create-workgroup to save current windows layout.

Use M-x wg-open-workgroup to open saved windows layout.
```

Please note old command `wg-switch-to-workgroup` is now alias of `wg-open-workgroup`.

You can use above commands without directly without turning on any minor mode.

I plan to remove the default keybinding and minor mode but the above commands are still valid. The default key bindings of minor mode might conflict with other minor modes.Using `global-set-key` is much better.

**Comment by sirikid** [comment]
`wg-prefix-key` doesn't work. @spavlovich001 can explain better.

**Comment by redguardtoo** [comment]
e0ffd03 enable wg-prefix-key (Chen Bin)
