### ISSUE TITLE
`wg-mode-line-string` not available anymore

### ISSUE THREAD

**Issue by myTerminal** [pashinin/workgroups2#103]
[My .emacs.d](https://github.com/myTerminal/.emacs.d/blob/c250eb2c13c7dd99a4f66b97b56614f36be5b1f2/emacs/myTerminal/basic/packages.el#L94) used to depend on `wg-mode-line-string` and I had it [added to telephone-line](https://github.com/dbordak/telephone-line/blob/aebac4658e553902369a3bf465bacc1f07a01106/telephone-line-segments.el#L319).

With the latest changes, the feature doesn't seem to exist anymore. Do you plan to bring it back in the future?

EDIT: Sorry about jumping straight into the issue, I ran an update after months and found myself in a total mess. I later realized that with what looks like a re-design to me, many other things are not working at this point. I also read through a few other issues where someone talked about using the one available through `melpa-stable`, so have pointed it to there for now. I should say, this one's one of my most used Emacs packages since I found it. Thank you!

**Comment by redguardtoo** [comment]
`wg-mode-line-string` is removed in code refactoring. The purpose of refactoring is focusing on key features, improved performance, make the code maintainable.

So save&load commands are regarded as key features and still available.

**Comment by myTerminal** [comment]
I'll keep an eye on the progress and till then will use the build from melpa-stable. I'll close this one as it's not an issue then.
