### ISSUE TITLE
trying to restore workgroup with org agenda gives error

### ISSUE THREAD

**Issue by rdiaz02** [pashinin/workgroups2#112]
With some of the recent changes (I think after 21 December 2021) workgroups with org agenda buffers are not restored. To reproduce:

```
emacs -Q
(require 'package)
(package-initialize)
(require 'workgroups2)
(setq wg-session-file "~/tmp/some_workgroups")

;; now open an org buffer and call org-agenda
(wg-create-workgroup "First workgroup")
```

Now, in another session do

```
emacs -Q
(setq wg-session-file "~/tmp/some_workgroups")
(wg-open-workgroup "First workgroup")
```
You get `switch-to-buffer: Wrong type argument: stringp, 0` and the org agenda buffer is not restored.

**Comment by redguardtoo** [comment]
d2e1f33 fixed special buffer bug (Chen Bin)

**Comment by rdiaz02** [comment]
Thanks a lot!! It is working again.
