### ISSUE TITLE
Keep frame name when saving workgroups?

### ISSUE THREAD

**Issue by phye** [pashinin/workgroups2#122]
Is it possible to save frame names when creating workgroups and support restoring frame names when open workgroup?

Currently, all my frame names are replaced with (F1..FN) when workgroups are restored.

**Comment by redguardtoo** [comment]
looks doable,
https://emacs.stackexchange.com/questions/58815/how-to-set-name-of-an-emacs-frame 

ping me if I have not implemented it this month. Or you can send me some PR.

**Comment by phye** [comment]
Sure，will have a try
