### ISSUE TITLE
[help] nov-mode buffer support, please

### ISSUE THREAD

**Issue by jsntn** [pashinin/workgroups2#124]
Hello, I've been using nov (https://melpa.org/#/nov) to read some EPUB documents.

Lately, I've been considering using workgroups2 to save and load the nov-mode buffers.
However, after checking the [add more special buffers support](https://github.com/pashinin/workgroups2/wiki/How-to-restore-a-specific-type-of-buffer) and some experimenting with it, I haven't had any luck making it work.

Could you please kindly help with this?

**Comment by redguardtoo** [comment]
nov works out of box at my computer. 

![图片](https://github.com/pashinin/workgroups2/assets/184553/bf513adc-719d-457c-97b6-12ecbd91e086)

BTW, if you need add support for some special buffer, check readme and some sample setup in my code.

**Comment by jsntn** [comment]
Thanks for the kind response!
I am going to check the config from my end, let me close this for now.
