### ISSUE TITLE
Issues when used together with ECB

### ISSUE THREAD

**Issue by jimeh** [pashinin/workgroups2#34]
I use ECB as a project directory tree browser with a single pane on the left side of the screen.

With Workgroups2 active, creating/switching workgroups starts duplicating the ECB frame (but with the active buffer in the new pane instead of the ECB buffer), till the duplicates fill up the whole screen. They can't be switched to with `C-x o` either, just like ECB's own panes.

To me this is massively painful, cause Workgroups2 is the dream replacement for Escreen/Elscreen I've been looking for for years, but at the same time I can't let go of having a project file/folder tree visible.

**Comment by redguardtoo** [comment]
See README. You can write your own code to support whatever buffer.

**Comment by jimeh** [comment]
Oh wow, I had forgotten about this issue. I even stopped using ECB about 3-4 years ago, and I've also migrated from escreen to tab-bar-mode and desktop.el for workspace management. But I'm curious to give workgroups2 another go to see if it'll suite my needs :)
