### ISSUE TITLE
`next-buffer` does nothing on restore

### ISSUE THREAD

**Issue by rubencaro** [pashinin/workgroups2#43]
All my visible buffers and windows are restored correctly when I start emacs. I even see all buffers, visible and not visible, on buffers list (C-x C-b). But if I try to change to any of them using `next-buffer` (or `previous-buffer`, `switch-to-next-buffer`, `switch-to-prev-buffer`...) then nothing happens. 

When I do change to one of the open but not visible buffers (using C-x b, for example), then I can change to this buffer again using `next-buffer`, but only this one buffer. The other open but not visible buffers remain unreachable using `next-buffer` commands. Until I reach them using C-x b. Then I can reach them. 

I can cycle only through the buffers I reached using C-x b. 

It behaves like some `cycling-buffer-list` is empty, and it rebuilds itself as I switch to buffers by C-x b.

Is this fixable?

**Comment by redguardtoo** [comment]
Latest version does not have this issue. Feel free to re-open this ticket.
