### ISSUE TITLE
Saving ALL buffers when doing <prefix> <C-s>

### ISSUE THREAD

**Issue by kaushalmodi** [pashinin/workgroups2#48]
Hi,

My emacs session has 98 buffers open. But when I do `<prefix> <C-s>`, I see that the saved session file stores only 6 buffer names!

I verified that that's happening by loading that saved session.

What am I missing in the config that workgroups2 is not saving all the buffers?

Here is how I am trying to save the workgroup with all open buffers:
- Open all the buffers I want to save in the workgroup (98 buffers)
- Create workgroup `<prefix> c`
- Save session `<prefix> C-s`
- Quit emacs
- Restart emacs
- Load session `<prefix> C-f`
  At this point all 98 buffers are not restored, only 6 of them are!

```
(req-package workgroups2
  :pre-load
  (progn
    ;; Change prefix key (before activating WG)
    (setq wg-use-default-session-file nil ; autoload/autosave (turn off for "emacs --daemon")
          wg-prefix-key (kbd "s-w") ;; Win + w
          wg-emacs-exit-save-behavior 'save
          wg-workgroups-mode-exit-save-behavior 'save
          wg-session-file (concat user-emacs-directory "/.emacs_workgroups")))
  :config
  (progn
    (workgroups-mode 1)))  ; put this at the bottom of .emacs
```

**Comment by redguardtoo** [comment]
Latest version does not have this issue. Feel free to re-open this ticket.
