### ISSUE TITLE
Keeping track of position in twittering-mode

### ISSUE THREAD

**Issue by 501st-alpha1** [pashinin/workgroups2#54]
I recently started using `workgroups2`, and like to keep one workgroup open with several `twittering-mode` buffers. In order to keep track of what I have read, I keep the point on the last tweet I've read, and usually `twittering-mode` inserts tweets above that point, letting me catch up at my own pace. However, when I switch back to this workgroup, the point is moved to where `workgroups2` thinks is the last place it was, even if that means it has skipped over several new tweets that have come in.

This also happened with the original `workgroups`, but not when I was using `elscreen`. (For other reasons, I'd rather not go back to the latter.) Also note that if I switch to a `twittering-mode` buffer from another workgroup with `C-x b`, it works as expected, with the point being on the last tweet I read, no matter it's current position in the buffer.

Is there a way to fix this?

**Comment by redguardtoo** [comment]
`twittering-mode` is not supported. But you can help yourself by some setup. See README.
