### ISSUE TITLE
Defining workgroups and switching projects

### ISSUE THREAD

**Issue by recifx** [pashinin/workgroups2#60]
I am running emacs 24.4.1 in a Windows 7 environment. 
I would like to create several workgroups each associated with a different project, and switch from one workgroup to the other, in each case having open only the buffers associated with the switched to workgroup. Is this possible with workgroups2? I tried the following:

I created the first workgroup wg0 using `wg-create-workgroup`, then opened several files that I wanted to be added to the workgroup, then `wg-save-session`, wrote to ~/.emacs_workgroups,  similarly with wg0, then exited. On reopening emacs, only some of the buffers from the previous session were reopened, and switching from one workgroup to the other  switched between the open buffers. I even tried `wg-associate-buffer-with-workgroup` to individually associate buffers with workgroups.

I have posted a gist of my .emacs_workgroups file:
https://gist.github.com/recifx/f4950fdd4caaef0830ca#file-emacs_workgroups

**Comment by redguardtoo** [comment]
Latest version does not have this issue. Feel free to re-open this ticket.
