### ISSUE TITLE
Workgroups 2 activates emacs window when it's enabled

### ISSUE THREAD

**Issue by sg2002** [pashinin/workgroups2#63]
Ok this is a really platform and WM specific issue, but in my case it's hugely distracting.

Every time when workgroups-mode is enabled, the main emacs window gets activated. But workgroups-mode is enabled anew every single time you open a new file.

This is bad because I use lazy load for my emacs desktop session and I may have like 40 files on it. I use windows and dexpot for virtual desktop support. Usually I start emacs on one virtual desktop and go do something else on another while it loads. With workgroups2 I get sent back to that desktop all 40 times.

**Comment by redguardtoo** [comment]
Latest version does not have this issue. Feel free to re-open this ticket.

Check README, just don't use `workgroups-mode`.
