### ISSUE TITLE
wg2 makes my buffer read-only

### ISSUE THREAD

**Issue by yeminzhang** [pashinin/workgroups2#64]
Hi,

When emacs starts up and window configurations are restored by wg2, some of the buffers become read-only. This is not reproducable all the time, but most of the time. Does anyone know why?

**Comment by neildurant** [comment]
I'm seeing the same thing....fairly irritating!

**Comment by redguardtoo** [comment]
can't reproduce the issue in latest version. feel free to re-open this ticket if you can reproduce.
