### ISSUE TITLE
For mac, it didn't save the windows.

### ISSUE THREAD

**Issue by yu-yuxuan** [pashinin/workgroups2#69]
Before I turn into Mac, the emacs can save the windows configuration in both windows and centos. But in the mac, as  long as I had turned off the emacs, I will see the initial windows when I reopen (as follows)

[quote];; This buffer is for notes you don't want to save, and for Lisp evaluation.
;; If you want to create a file, visit that file with C-x C-f,
;; then enter the text in that file's own buffer.[/quote]

How can I deal with that? Thank you very much. 

In the _Messages_, 
It shows:
`Error finding`wg-session-file': (error Window #<window 3 on *scratch*> too small for splitting 3)
Workgroups Mode: on`

**Comment by redguardtoo** [comment]
Latest version does not have this issue. Feel free to re-open this ticket.
