### ISSUE TITLE
No maintainer (fork it all)

### ISSUE THREAD

**Issue by pashinin** [pashinin/workgroups2#73]
I kinda stopped writing this extension in Elisp. (Fork it, do whatever you want, can make you a maintainer) I think such extension should be written in Emacs code.
I started to do it in C and met even more problems than with Lisp but still...

**Comment by redguardtoo** [comment]
Hi, @pashinin , I'd like to take over this project. Surely it will keep using lisp.

**Comment by pashinin** [comment]
@redguardtoo, added you to collaborators

**Comment by redguardtoo** [comment]
@pashinin , thank you.

I'd like to focus on restoring as many types of buffer as possible. I will also import two new commands save/load-workgroup. Many legacy commands will be cleaned up. Emacs 24.4 is required.


Could be a radical change. If you are still using some old command,  might be inconvenience? You are OK with that?

**Comment by pashinin** [comment]
I'm ok, but breaking changes should be done carefully

**Comment by Pitometsu** [comment]
@redguardtoo thank you for maintaining. I really enjoy this plugin in my work. Please, try to keep an ability to have a same workgroups list in different frames/clients to switch around independently.

What it would be really awesome is to have here a some kind of support of full-screen ui plugins like https://github.com/ralesi/ranger.el or ediff or sunrise-commander or edbi. It would be handy to open such a full-screen-required plugins in new workspace all the time to preserve ability to switch to the previous one back. However not sure yet are those full-screen UI really follows emacs-way of doing UI.

**Comment by tomdavey** [comment]
I also say “thank you!” 

 

Workgroups is my essential Emacs extension. I invariably work with several dozen open buffers at a time. Quickly finding the buffers I need, and keeping their windows properly sized with the position of point remembered, would be impossible without Workgroups.

 

--  

Tom Davey

tom@tomdavey.com <mailto:tom@tomdavey.com> 

New York NY USA
