### ISSUE TITLE
Feature suggestion - clear workspace and clear workspace before loading

### ISSUE THREAD

**Issue by cjohansson** [pashinin/workgroups2#77]
Hi!

I think this plugin is great. Thank you for your work on it. The only thing I miss is the ability to clear a workspace. Like when I go from one project to another I would like the existing buffers killed before opening the new workspace. Now there is a lot of buffers opened that are irrelevant to the project and I manually close them.

**Comment by redguardtoo** [comment]
Latest version does not have this issue. Feel free to re-open this ticket.
