### ISSUE TITLE
Fullscreen window plugins integration (e.g. ranger.el)

### ISSUE THREAD

**Issue by Pitometsu** [pashinin/workgroups2#80]
See https://github.com/ralesi/ranger.el/issues/124

It would be nice to have ability run full-frame plugins in separate workspaces. Is it possible?
Like eshell, sunrise commander, ranger...

**Comment by redguardtoo** [comment]
wg2 support frames. How to create a new frame and run whatever command (eshell, ranger, ...) is decided by users.

**Comment by Pitometsu-GeniusYield** [comment]
@redguardtoo wg2 can be used in terminal as well.

What I mean, there's a lot of "full-screen" plugins, like ranger, edbi, jabber.  So that would be very convenient to automatically open them in the new work-group.
