### ISSUE TITLE
feature requests: use ido-style buffer names

### ISSUE THREAD

**Issue by notuntoward** [pashinin/workgroups2#81]
When switching between names workgroups, it would be nice to use ido-style name matching, in the way that ido does when switching between buffers.

**Comment by redguardtoo** [comment]
We use `completing-read` api which supports any modern selection framework (ivy, helm, ...). We don't have resource to support ido.

**Comment by notuntoward** [comment]
Thanks for the response.

I wasn't suggesting that you support ido.  I only meant to suggest uniquifing buffer names like ido does.  Uniquifying is [built into icomplete](https://www.gnu.org/software/emacs/manual/html_node/emacs/Uniquify.html) and[ emacs comes with a library](https://www.emacswiki.org/emacs/uniquify) to do this.
