### ISSUE TITLE
Attemp to pickel unpickelable type

### ISSUE THREAD

**Issue by kahrkunne** [pashinin/workgroups2#86]
Getting this error (verbatim, including spelling mistakes) whenever I try to call wg-save-session. I'm not sure what that means...

**Comment by tdavey** [comment]
If by "spelling mistakes" you are referring to the verb "pickel" and its derivatives, those are not spelling mistakes. See the docs on the Wiki: https://github.com/pashinin/workgroups2/wiki. 

I am not the developer, just a user of this excellent extension, so I'm afraid I can't help you. However, if you can't get Workgroups 2 to save a session, I find that Workgroups 1 still works perfectly well with recent versions of Emacs.

**Comment by kahrkunne** [comment]
I assumed "pickel" was a spelling mistake, but I might be wrong. "Attemp" definitely is, though.

**Comment by pashinin** [comment]
It's abandoned. Feel free to fork it or become a maintainer. You are welcome https://github.com/pashinin/workgroups2/issues/73

**Comment by kahrkunne** [comment]
Oh, I didn't notice. My bad.

**Comment by dsweber2** [comment]
@redguardtoo if you happen to still be working on workgroups2, this bug comes up if I have multiple OS windows open. Thanks for picking it up at all, it's been a useful package!

**Comment by redguardtoo** [comment]
@dsweber2 , I need more details before working on this issue.

**Comment by dsweber2** [comment]
fair enough. Emacs version 26.3, workgroups2 version 20200613.1307 installed via melpa.
Relevant settings in my .emacs
```
(require 'workgroups2)
;; Change some settings
(setq wg-session-load-on-start t)
(setq wg-emacs-exit-save-behavior           'save)
(setq wg-workgroups-mode-exit-save-behavior 'save)
(workgroups-mode 1)        ; put this one at the bottom of .emacs (init.el)
```

This happens when I use emacs as a standalone program (not in the terminal), and having multiple frames/windows open (as in desktop windows). when I try to save, it gives me the above error. If there's a way to get a more detailed error log, I can give that a shot.

**Comment by redguardtoo** [comment]
See the latest version.

**Comment by dsweber2** [comment]
wow that was fast, thanks! It's working
