### ISSUE TITLE
plan to refactor workgroups2

### ISSUE THREAD

**Issue by redguardtoo** [pashinin/workgroups2#87]
- 24.4 is required
- update CI, unit test
- use completing-read (so user could use ido/ivy/helm to select workgroup)
- add save/load workgroup
- don't enable `workgroups-mode`
- remove dependency on `f` and `anaphora`, `ring`

**Comment by luluman** [comment]
Workgroups2 is excellent for working on remote. It can restore all my workgroups when I reattach emacs daemon. But sometimes it consumes a lot of CPU and emacs stuck. Also, emacs raise a lot of warring when compiling Workgroups2, which I guess Workgroups2 maybe using some function emacs obsoleted.
I am looking forward to someone maintain this project, and appreciate @redguardtoo can do this. Thank you.

**Comment by redguardtoo** [comment]
Sure. I will definitely keep maintaining this excellent project. I've been happily using workgroups2 for 6 years.

**Comment by luluman** [comment]
Wow cool！

**Comment by MoHKale** [comment]
That's nice to hear. I just spent the day trying to set up workgroups on my config... only to find it hasn't been updated in 8 years 😢😢😢 (explains why I couldn't get it to start without throwing errors). Could you maybe include a section in the README explaining the difference between this workgroups2 and the original workgroups. I see a lot of similair functionality & commands so I'm curious. Thnx.

**Comment by redguardtoo** [comment]
refactor is mostly done. Now my focus is to support more modes.

**Comment by simonmichael** [comment]
Thanks again. I have opened #108 to discuss removed keybindings. I echo @mohkale in 2019, it would be great to have a changelog, version number bump, and perhaps a release.
