### ISSUE TITLE
How to automatically perform wg-save-session?

### ISSUE THREAD

**Issue by fu123456** [pashinin/workgroups2#93]
It seems to only execute "wg-save-session" command by my hand, which can save sessions. So I want to automatically
auto save sesstions to my file ".emacs_workgroup". My config is
```eslip
;; What to do on Emacs exit / workgroups-mode exit?
(setq wg-emacs-exit-save-behavior           'save)      ; Options: 'save 'ask nil
(setq wg-workgroups-mode-exit-save-behavior 'save)      ; Options: 'save 'ask nil
```
It does not work. 
How to solve this issue.

**Comment by redguardtoo** [comment]
maybe `(wg-save-session t)` in `auto-save-hook`?

**Comment by fu123456** [comment]
I add the below code to my config:
``` elisp
;; auto save wg-save-session
(add-hook 'auto-save-hook 'wg-save-session t)
```
But it does not work.

**Comment by redguardtoo** [comment]
Sorry, it's my typo, should be `after-save-hook`,
```
(defun after-save-hook-setup ()
  (wg-save-session t))
(add-hook 'after-save-hook 'after-save-hook-setup)
```

Personally I don't like auto save the sub-windows layout. I might change the layout temporarily. The temp layout should not be saved.

**Comment by redguardtoo** [comment]
Now it's all handled automatically.
