### ISSUE TITLE
Rules for reviving/recreating special buffers

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [pashinin/workgroups2#94]
There are some buffers workgroups2 needs help reviving. Some such buffers are exwm buffers as well as w3m and eww buffers. I was wondering if there is a way workgroups2 provides that allows the user to tell it how to handle these "special" buffers. If there isn't, I think that adding such a feature would be very nice.

**Comment by Luis-Henriquez-Perez** [comment]
Bad question. I saw the documentation. I'll post my rule for exwm here when I write it.

**Comment by redguardtoo** [comment]
cool look forward to it. You can send me the pull request to update README.
